kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-stateless-example
  namespace: default
  generation: 3
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-stateless-example
  template:
    metadata:
      labels:
        app: iot-stateless-example
    spec:
      containers:
        - name: iot-stateless-example
          image: bjimerson/isostatelessexample:latest
          ports:
            - containerPort: 10000
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
